apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  template:
    spec:
      containers:
        - name: grafana
          env:
            - name: GF_AUTH_GOOGLE_ENABLED
              value: "true"
            - name: GF_AUTH_GOOGLE_CLIENT_ID
              value: "my-client-id"
            - name: GF_AUTH_GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: grafana-google-auth
                  key: google-auth-client-secret
            - name: GF_AUTH_GOOGLE_SCOPES
              value: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
            - name: GF_AUTH_GOOGLE_AUTH_URL
              value: https://accounts.google.com/o/oauth2/auth
            - name: GF_AUTH_GOOGLE_TOKEN_URL
              value: https://accounts.google.com/o/oauth2/token
            - name: GF_AUTH_GOOGLE_ALLOWED_DOMAINS
              value: utilitywarehouse.co.uk
            - name: GF_AUTH_GOOGLE_ALLOW_SIGN_UP
              value: "true"
