apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    kubernetes.io/ingress.class: traefik-private
  annotations:
    external-dns.alpha.kubernetes.io/target: in-k8s.dev.uw.systems
  name: grafana
