apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base/
#  - github.com/utilitywarehouse/grafana-manifests/base?ref=v1.0.10
patchesStrategicMerge:
  - grafana.yaml
configMapGenerator:
  - name: grafana
    files:
      - datasources.yaml=resources/datasources.yaml
      - dashboards.yaml=resources/dashboards.yaml
secretGenerator:
  - name: grafana-secrets
    type: Opaque
    files:
      - admin-password=secrets/grafana-admin-password
      - git-ssh-key=secrets/grafana-git-ssh-key
      - google-auth-client-secret=secrets/grafana-google-auth-client-secret
      - known_hosts=secrets/grafana-known_hosts
